"""add pseudo_streaming_enabled to system_config

Revision ID: 79c087902f1c
Revises: ddb8814b35c9
Create Date: 2025-12-04 17:17:29.188142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c087902f1c'
down_revision: Union[str, Sequence[str], None] = 'ddb8814b35c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('pseudo_streaming_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'pseudo_streaming_enabled')
    # ### end Alembic commands ###
