"""Allow key reuse across different channels

Revision ID: a6b8ff377278
Revises: 6c89eaa96115
Create Date: 2025-12-01 20:38:37.864872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b8ff377278'
down_revision: Union[str, Sequence[str], None] = '6c89eaa96115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_keys', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_official_keys_key'))
        batch_op.create_index(op.f('ix_official_keys_key'), ['key'], unique=False)
        batch_op.create_unique_constraint('_user_channel_key_uc', ['key', 'user_id', 'channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_keys', schema=None) as batch_op:
        batch_op.drop_constraint('_user_channel_key_uc', type_='unique')
        batch_op.drop_index(op.f('ix_official_keys_key'))
        batch_op.create_index(op.f('ix_official_keys_key'), ['key'], unique=1)
    # ### end Alembic commands ###
